#!/bin/bash
OWNER_U=
OWNER_G=

usage() {
  echo "$0 -u <DEST_OWNER_USER> -g <DEST_OWNER_GROUP> <SRCDIR> <DESTDIR>"
  exit 1;
}

# Process options to set owning user (-u) and group (-g) of destination tree.

while [[ $1 = -* ]] ; do
  if [ "$1" = "-g" ]; then
    OWNER_G="$2"; shift 2
  fi
  if [ "$1" = "-u" ]; then
    OWNER_U="$2"; shift 2
  fi
done

# Print usage if wrong number of options, or if either of -u or -g is omitted.

[ $# -ne 2 -o  \
  -z "$OWNER_U" -o \
  -z "$OWNER_G" ] && { usage; }

# Copy source tree to destination tree, applying tar's ability to modify the owning user and group.

(cd $1 && tar --owner=$OWNER_U --group=$OWNER_G -cf - .) |\
(cd $2 && sudo tar  -xf - .)

