#!/usr/bin/env python
from __future__ import print_function
import os, sys
from os.path import expanduser, basename

MODULE_CONF_DIR  = "/var/lib/irods"
sys.path.insert(0,MODULE_CONF_DIR) # --> locate 'compute' module/conf dir
from compute.common import session_object # , detect_file_location

program = sys.argv[0]

def get_usage():
  return ( "USAGE: "
  "{0}  arg1  arg2\n"
  "  arg1 = logical path to data object input\n"
  "  arg2 = resource name\n"
  ). format(basename(program))

try:
  obj_logical_path , resc_name = sys.argv[1:]
except:
  print (get_usage(), file = sys.stderr); exit(1)


def detect_file_location( irods_dataObj_path , resc_name ):

   session = session_object()
   if '/' not in irods_dataObj_path:
     defaultCollection = "/{}/home/{}".format(session.zone,session.username)
     irods_dataObj_path = "{}/{}".format(defaultCollection,irods_dataObj_path)
   data_object = session.data_objects.get (irods_dataObj_path)
   all_replicas = data_object.replicas
   this_repl = [ o for o in all_replicas \
                 if o.resource_name == resc_name ]
   return None if not(this_repl) else this_repl[0].path

#=-=-=-=-=-=-=-=-=-=-=-=-=-MAIN PROGRAM=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
phys_path = detect_file_location( obj_logical_path, resc_name )

if phys_path: print (phys_path, end='', file = sys.stdout )
