#!/bin/bash
## Debug only:
#  echo $0  `date` >>/tmp/prolog

#-- Metadata trail

UUID=$(uuidgen -t)
MUTX=$(hostname)_slurmjob_${SLURM_JOB_ID}.txt
touch /tmp/$MUTX
iput /tmp/$MUTX && {	imeta add -d $MUTX uuid $UUID 
			imeta add -d $MUTX slurm_job $SLURM_JOB_ID ; }

