#!/bin/bash

. /var/lib/irods/compute/irods_compute_functions

thumbnail_size=$(get_irods_slurm_var "size_string")
if [ $? -eq 0 ] ; then
    python /var/lib/irods/compute/common.py reg_repl_trim_output "$thumbnail_size"
fi

UUID=$(get_irods_slurm_var uuid) 

destroy_irods_slurm_desc

#   -- debug --
if [ -n "$UUID" ] ; then 
  echo $0  `date` $UUID >>/tmp/epilog 
fi
