#!/bin/bash

FUNCTIONS=/var/lib/irods/compute/irods_compute_functions
if [ -r $FUNCTIONS ]; then
  . $FUNCTIONS

UUID=$(
  create_irods_slurm_desc -v  # -- create time-based UUID for this job
)

#   -- debug --
[ -n "$UUID" ] && { # echo >>"/tmp/$UUID" # - suppresses epilog deletion of UUID
  echo $0  `date` "$UUID" >>/tmp/prolog ; }

fi # -r $FUNCTIONS
